addReviewers: true

addAssignees: true

reviewers: 
  - NGPixel

# A pull request whose title contains one of these gets no reviewers
skipKeywords:
  - wip

# 0 adds all the reviewers
numberOfReviewers: 0
