import { useRouter, useRoute } from 'vue-router'

import { routableHref } from '@/helpers/renderedContent'
import { localizedPagePath } from '@/helpers/pagePaths'

import { usePageStore } from '@/stores/page'
import { useSiteStore } from '@/stores/site'

/**
 * Schemes `destination()` will still hand out as a plain `href` once `routableHref` has declined an
 * address (see below) -- `http:`/`https:` for an ordinary external link, `mailto:`/`tel:` because
 * those are legitimate nav item destinations with no script-execution risk. Anything else --
 * `javascript:` chief among them -- gets no `href` at all: Vue does not sanitize a dynamically bound
 * one, and a `<w-item>` rendered from a nav item is exactly such a binding (OpenProject #2208 §3).
 */
const SAFE_TARGET_PROTOCOLS = new Set(['http:', 'https:', 'mailto:', 'tel:'])

/**
 * Where a nav item points, and whether it is the page being read -- used by `NavSidebarItem.vue`,
 * which renders itself once per nesting level (OpenProject #814). Kept as a composable rather than
 * methods on that component so every recursive instance calls the same implementation instead of
 * each one closing over its own copy.
 */
export function useNavSidebarDestination() {
  const router = useRouter()
  const route = useRoute()
  const pageStore = usePageStore()
  const siteStore = useSiteStore()

  /**
   * Where a nav item points, as the props that take a reader there.
   *
   * An administrator types this address by hand and it can be anything: a path in this wiki, a URL on
   * another site, a `mailto:`. Only the first of those is the router's, and handing it the others is what
   * made an external link land on "This page does not exist yet" -- vue-router matched
   * `https://example.com/x` as a PATH, found nothing, and fell through to the catch-all page view.
   *
   * The question is the one `routableHref` already answers for the links inside a rendered page, so it is
   * the same function that answers it here rather than a second opinion that can drift from it. Which also
   * settles two cases beyond the reported one: an item pointing into `/_files/` now downloads the file
   * instead of 404ing, and one pointing at `#a-heading` on this page jumps to it.
   *
   * `openInNewWindow`, set per link in the navigation editor, is fed into the same question rather than
   * added on afterwards: a link asking for a new tab is one `routableHref` declines whatever it points at,
   * on the grounds that a new context is the browser's to open and not the router's to swap in. So such an
   * item goes out as a plain anchor -- which loads this app fresh in the new tab, which is what a new tab
   * does in any case.
   *
   * Mind the two meanings of "target" in here: a nav item's is the address to go to, an anchor's is the
   * window to open it in.
   *
   * An item with no `target` at all -- an empty folder generated by `generateFromTree()`
   * (`models/navigation.ts`, OpenProject #2515), which survives into the tree as a leaf for an actor who
   * could populate it rather than being dropped as a dead end -- falls back to its own `path`, run
   * through the same `localizedPagePath` every other in-app link in the SPA builds through, rather than
   * unconditionally `/`. Landing there hits the ordinary "this page doesn't exist yet" flow, which is the
   * right destination for a folder with nothing in it yet. Without this, every empty folder resolved to
   * the same home route and, once there, every one of them read as "selected" simultaneously (OpenProject
   * #2528).
   *
   * `pageStore.locale` is the right locale to build that link in, not a per-item field: the whole tree
   * handed to this composable was fetched for one locale at a time (`NavSidebar.vue`'s watcher refetches
   * on `pageStore.navigationId`, which changes precisely when the page being read -- and so its locale --
   * changes), so there is no separate per-row locale to read.
   *
   * Two typed-address cases worth calling out explicitly (task 466 verified both rather than assuming):
   *
   *   - `mailto:` (and `tel:`) need no special-casing to keep working here, only `SAFE_TARGET_PROTOCOLS`
   *     naming them: `routableHref`'s protocol check (`/^https?:$/`) already declines anything that is
   *     not http(s), so either falls through to the plain `href` branch below, and — since its protocol
   *     is on the allowlist — the browser opens it with the reader's mail client or dialer, same as any
   *     other link on the page. An address whose protocol is NOT on the allowlist (`javascript:` above
   *     all) reaches that same fallback and gets nothing: no `href` for Vue to bind (OpenProject
   *     #1360/#2208, 2026-08-24 security audit §3).
   *   - A bare domain typed without a scheme -- `example.com` rather than `https://example.com` -- is NOT
   *     declined. `new URL('example.com', location.href)` resolves it as a same-origin PATH relative to
   *     whatever page is open, so `routableHref` hands it to the router, which then renders "page not
   *     found" for an address the author meant as external. This is not a bug to fix here: it is exactly
   *     how a bare `<a href="example.com">` behaves in any HTML document, including this wiki's own
   *     rendered page content, which asks `routableHref` the identical question for the identical reason.
   *     Guessing "this looks like a domain" would be a heuristic this codebase does not apply to content
   *     links, and applying it only to nav items would make the two inconsistent. Typing the full address
   *     with its scheme is the author's responsibility, the same as it is when writing a link into a page.
   */
  function destination(item) {
    const address =
      item.target ??
      (item.path ? localizedPagePath(item.path, pageStore.locale, siteStore.localeRouting) : '/')
    const target = item.openInNewWindow ? '_blank' : undefined
    let url = null
    try {
      url = new URL(address, globalThis.location.href)
    } catch {
      // -> Not a URL at all: nothing to route to, and nothing safe to bind as an <a href> either
      return {}
    }
    const routable = routableHref({ href: url.href, target }, globalThis.location)
    if (routable) {
      return { to: routable }
    }
    // -> An ordinary external link (or mailto:/tel:), or nothing: `address` is author-supplied, and
    //    `javascript:` bound as a dynamic href is script this page would run on click -- mirrors
    //    `Index.vue#relationLink`'s check for the same reason, widened for the two extra protocols a
    //    nav item legitimately points at (OpenProject #1360/#2208, 2026-08-24 security audit §3).
    return SAFE_TARGET_PROTOCOLS.has(url.protocol) ? { href: address, target } : {}
  }

  /**
   * Whether a nav item points at the page being read.
   *
   * Only a routed item can be: an address that leaves the wiki is never where the reader already is, and
   * one that opens in a new tab is not asking to be here either. Asked of the router rather than compared
   * as strings, so a trailing slash, an escape or a redirect is settled the same way the router settles it
   * when the reader actually clicks.
   *
   * This is only used to decide which groups open on arrival. The dent itself is drawn off
   * `router-link-exact-active`, the class `RouterLink` puts on the row it has taken the reader to -- the
   * same question, answered by the same router, but kept up to date by the link itself as the reader moves
   * around rather than recomputed here.
   *
   * Confirmed (task 466), not assumed, against two cases that both go through `router.resolve()`:
   *
   *   - A trailing-slash variant of a target's path (`/foo/bar/` typed where the page is `/foo/bar`, or
   *     vice-versa) does NOT match. `router.resolve()` does not normalize a trailing slash -- it is a
   *     genuinely different path to the router, not an ambiguity this function is getting wrong -- so
   *     typing one correctly is on the author, same as the address cases in `destination()`'s own doc.
   *   - A page reached through a redirect (this wiki's alias route, `/a/:alias`, whose `beforeEnter`
   *     resolves and redirects to the page's real path) DOES match, with no special-casing needed: once
   *     the redirect has settled, `route.path` is the real page's path, and a nav item -- which can only
   *     ever be authored with that real path, since the navigation editor's picker addresses pages by it,
   *     never by an alias -- resolves to the same string through the same router.
   */
  function isCurrent(item) {
    const { to } = destination(item)
    return Boolean(to) && router.resolve(to).path === route.path
  }

  /**
   * Whether one of a group's children -- at any depth -- is the page being read, which is what opens
   * the group. Recurses through nested `children` so a group auto-opens for a reader who arrived
   * several folders deep, not only when the current page is a direct child.
   */
  function containsCurrent(item) {
    return (item.children ?? []).some((child) => isCurrent(child) || containsCurrent(child))
  }

  return { destination, isCurrent, containsCurrent }
}
