import { useRouter, useRoute } from 'vue-router'

import { routableHref } from '@/helpers/renderedContent'
import { localizedPagePath } from '@/helpers/pagePaths'

import { usePageStore } from '@/stores/page'
import { useSiteStore } from '@/stores/site'

/**
 * Schemes `destination()` will still hand out as a plain `href` once `routableHref` has declined an
 * address (see below) -- `http:`/`https:` for an ordinary external link, `mailto:`/`tel:` because
 * those are legitimate nav item destinations with no script-execution risk. Anything else --
 * `javascript:` chief among them -- gets no `href` at all: Vue does not sanitize a dynamically bound
 * one, and a `<w-item>` rendered from a nav item is exactly such a binding (OpenProject #2208 §3).
 */
const SAFE_TARGET_PROTOCOLS = new Set(['http:', 'https:', 'mailto:', 'tel:'])

/**
 * The knowledge graph's fixed route path (`router/routes.js`) -- no locale prefix, unlike an
 * ordinary content page. `graphSidebarBranch()` below is the sidebar half of OpenProject #3313's
 * branching; `components/HeaderNav.vue`'s Graph nav button owns the other half and carries the same
 * literal, since the two are independent call sites rather than a shared import worth adding for one
 * string.
 */
const GRAPH_ROUTE_PATH = '/_graph'

/**
 * Where a nav item points, and whether it is the page being read -- used by `NavSidebarItem.vue`,
 * which renders itself once per nesting level (OpenProject #814). Kept as a composable rather than
 * methods on that component so every recursive instance calls the same implementation instead of
 * each one closing over its own copy.
 */
export function useNavSidebarDestination() {
  const router = useRouter()
  const route = useRoute()
  const pageStore = usePageStore()
  const siteStore = useSiteStore()

  /**
   * Where a nav item points, as the props that take a reader there.
   *
   * An administrator types this address by hand and it can be anything: a path in this wiki, a URL on
   * another site, a `mailto:`. Only the first of those is the router's, and handing it the others is what
   * made an external link land on "This page does not exist yet" -- vue-router matched
   * `https://example.com/x` as a PATH, found nothing, and fell through to the catch-all page view.
   *
   * The question is the one `routableHref` already answers for the links inside a rendered page, so it is
   * the same function that answers it here rather than a second opinion that can drift from it. Which also
   * settles two cases beyond the reported one: an item pointing into `/_files/` now downloads the file
   * instead of 404ing, and one pointing at `#a-heading` on this page jumps to it.
   *
   * `openInNewWindow`, set per link in the navigation editor, is fed into the same question rather than
   * added on afterwards: a link asking for a new tab is one `routableHref` declines whatever it points at,
   * on the grounds that a new context is the browser's to open and not the router's to swap in. So such an
   * item goes out as a plain anchor -- which loads this app fresh in the new tab, which is what a new tab
   * does in any case.
   *
   * Mind the two meanings of "target" in here: a nav item's is the address to go to, an anchor's is the
   * window to open it in.
   *
   * An item with no `target` at all -- an empty folder generated by `generateFromTree()`
   * (`models/navigation.ts`, OpenProject #2515), which survives into the tree as a leaf for an actor who
   * could populate it rather than being dropped as a dead end -- falls back to its own `path`, run
   * through the same `localizedPagePath` every other in-app link in the SPA builds through, rather than
   * unconditionally `/`. Landing there hits the ordinary "this page doesn't exist yet" flow, which is the
   * right destination for a folder with nothing in it yet. Without this, every empty folder resolved to
   * the same home route and, once there, every one of them read as "selected" simultaneously (OpenProject
   * #2528).
   *
   * `pageStore.locale` is the right locale to build that link in, not a per-item field: the whole tree
   * handed to this composable was fetched for one locale at a time (`NavSidebar.vue`'s watcher refetches
   * on `pageStore.navigationId`, which changes precisely when the page being read -- and so its locale --
   * changes), so there is no separate per-row locale to read.
   *
   * Two typed-address cases worth calling out explicitly (task 466 verified both rather than assuming):
   *
   *   - `mailto:` (and `tel:`) need no special-casing to keep working here, only `SAFE_TARGET_PROTOCOLS`
   *     naming them: `routableHref`'s protocol check (`/^https?:$/`) already declines anything that is
   *     not http(s), so either falls through to the plain `href` branch below, and — since its protocol
   *     is on the allowlist — the browser opens it with the reader's mail client or dialer, same as any
   *     other link on the page. An address whose protocol is NOT on the allowlist (`javascript:` above
   *     all) reaches that same fallback and gets nothing: no `href` for Vue to bind (OpenProject
   *     #1360/#2208, 2026-08-24 security audit §3).
   *   - A bare domain typed without a scheme -- `example.com` rather than `https://example.com` -- is NOT
   *     declined. `new URL('example.com', location.href)` resolves it as a same-origin PATH relative to
   *     whatever page is open, so `routableHref` hands it to the router, which then renders "page not
   *     found" for an address the author meant as external. This is not a bug to fix here: it is exactly
   *     how a bare `<a href="example.com">` behaves in any HTML document, including this wiki's own
   *     rendered page content, which asks `routableHref` the identical question for the identical reason.
   *     Guessing "this looks like a domain" would be a heuristic this codebase does not apply to content
   *     links, and applying it only to nav items would make the two inconsistent. Typing the full address
   *     with its scheme is the author's responsibility, the same as it is when writing a link into a page.
   */
  function destination(item) {
    const address =
      item.target ??
      (item.path ? localizedPagePath(item.path, pageStore.locale, siteStore.localeRouting) : '/')
    const target = item.openInNewWindow ? '_blank' : undefined
    let url = null
    try {
      url = new URL(address, globalThis.location.href)
    } catch {
      // -> Not a URL at all: nothing to route to, and nothing safe to bind as an <a href> either
      return {}
    }
    const routable = routableHref({ href: url.href, target }, globalThis.location)
    if (routable) {
      return graphSidebarBranch(item) ?? { to: routable }
    }
    // -> An ordinary external link (or mailto:/tel:), or nothing: `address` is author-supplied, and
    //    `javascript:` bound as a dynamic href is script this page would run on click -- mirrors
    //    `Index.vue#relationLink`'s check for the same reason, widened for the two extra protocols a
    //    nav item legitimately points at (OpenProject #1360/#2208, 2026-08-24 security audit §3).
    return SAFE_TARGET_PROTOCOLS.has(url.protocol) ? { href: address, target } : {}
  }

  /**
   * OpenProject #3313: while `/_graph` is open, clicking a page item in the sidebar moves the
   * graph's own root (`route.query.path` -- the Feature's shared query-param contract, #3311/#3312)
   * instead of navigating away -- except the item that IS the currently active root, which falls
   * through (returns `null`, so `destination()` uses its ordinary `{ to }`) and navigates normally,
   * the same "exit the graph and go read that page" behavior clicking it from anywhere else already
   * has.
   *
   * OpenProject #3362: a PAGE item anchors on its own PARENT folder, not itself -- mirroring
   * `HeaderNav.vue#onGraphNavClick()`'s #3337 fix (`pageStore.folderPath`, not `pageStore.path`) for
   * the identical reason: anchoring a page on itself shows only that one page (it has no
   * descendants), not the folder of related pages a reader selecting it almost always wants, and
   * gives a top-level page no useful anchor at all short of showing the whole wiki -- which is
   * exactly the parent-folder-is-root case handles. An (empty) FOLDER item -- also routed through
   * this same leaf branch, since `NavSidebarItem.vue` renders an empty folder as a leaf -- anchors on
   * ITSELF, unchanged: `reanchorGraphOnFolder()` below establishes that "anchor on the folder, not
   * its parent" is correct for an intentionally-selected folder (#3353), and an empty one is no
   * exception. `item.isFolder` (not `item.children?.length > 0`, which is false for an empty folder
   * by definition) is what `NavSidebarItem.vue` itself already uses to tell the two apart.
   *
   * Reads `route.query.path` directly, in the same raw un-prefixed form `item.path` already carries
   * (`backend/models/navigation.ts`'s own doc comment on `NavigationItem.path`), rather than
   * anything `pages/Graph.vue` computes internally -- the epic plan's own cross-task file-ownership
   * split keeps this composable off Graph.vue's locale-scoped node identity entirely. The parent-path
   * computation mirrors `stores/page.js`'s `folderPath` getter exactly (`path.split('/').slice(0,
   * -1).join('/')`), generalized to an arbitrary nav item's path rather than the currently-read
   * page's -- there is no shared helper for it since `folderPath` is a store getter, not a function.
   *
   * `router.replace`, not `router.push`: repeatedly re-rooting the graph from the sidebar must not
   * spam the browser history with one entry per click.
   *
   * Only for a nav item that carries its own `path` -- a generated tree item, page or folder. A
   * hand-authored `static` link (no `item.path`) may not correspond to a real page at all, so it
   * keeps navigating normally even inside the graph.
   *
   * @returns {{ clickable: true, onClick: Function } | null}
   */
  function graphSidebarBranch(item) {
    if (route.path !== GRAPH_ROUTE_PATH || !item.path || isAnchor(item)) {
      return null
    }
    const anchorPath = item.isFolder ? item.path : item.path.split('/').slice(0, -1).join('/')
    return {
      clickable: true,
      onClick: () => router.replace({ path: GRAPH_ROUTE_PATH, query: { path: anchorPath } })
    }
  }

  /**
   * Whether a nav item points at the page being read.
   *
   * Only a routed item can be: an address that leaves the wiki is never where the reader already is, and
   * one that opens in a new tab is not asking to be here either. Asked of the router rather than compared
   * as strings, so a trailing slash, an escape or a redirect is settled the same way the router settles it
   * when the reader actually clicks.
   *
   * This is only used to decide which groups open on arrival. The dent itself is drawn off
   * `router-link-exact-active`, the class `RouterLink` puts on the row it has taken the reader to -- the
   * same question, answered by the same router, but kept up to date by the link itself as the reader moves
   * around rather than recomputed here.
   *
   * Confirmed (task 466), not assumed, against two cases that both go through `router.resolve()`:
   *
   *   - A trailing-slash variant of a target's path (`/foo/bar/` typed where the page is `/foo/bar`, or
   *     vice-versa) does NOT match. `router.resolve()` does not normalize a trailing slash -- it is a
   *     genuinely different path to the router, not an ambiguity this function is getting wrong -- so
   *     typing one correctly is on the author, same as the address cases in `destination()`'s own doc.
   *   - A page reached through a redirect (this wiki's alias route, `/a/:alias`, whose `beforeEnter`
   *     resolves and redirects to the page's real path) DOES match, with no special-casing needed: once
   *     the redirect has settled, `route.path` is the real page's path, and a nav item -- which can only
   *     ever be authored with that real path, since the navigation editor's picker addresses pages by it,
   *     never by an alias -- resolves to the same string through the same router.
   */
  function isCurrent(item) {
    const { to } = destination(item)
    return Boolean(to) && router.resolve(to).path === route.path
  }

  /**
   * Whether one of a group's children -- at any depth -- is the page being read, which is what opens
   * the group. Recurses through nested `children` so a group auto-opens for a reader who arrived
   * several folders deep, not only when the current page is a direct child.
   */
  function containsCurrent(item) {
    return (item.children ?? []).some((child) => isCurrent(child) || containsCurrent(child))
  }

  /**
   * OpenProject #3362/#3365: whether `item` is the page/folder the knowledge graph is currently
   * anchored on -- the same three-part check `graphSidebarBranch()` and `reanchorGraphOnFolder()`
   * already used privately as a no-op guard (OpenProject #3313/#3353), now factored out and
   * exported so `NavSidebarItem.vue` can bind its anchor indicator off the identical test rather
   * than a third inline copy. Both guards below call this in place of their own former inline
   * condition; neither's behavior changes.
   *
   * Deliberately compares the RAW, un-prefixed `item.path` against `route.query.path` -- the same
   * raw form both guards already used and `graphSidebarBranch()`'s own doc comment above explains
   * (`backend/models/navigation.ts`'s `NavigationItem.path`) -- never through `localizedPagePath()`
   * or any other normalization, which would drift out of sync with the actual anchor `pages/Graph.vue`
   * reads and writes.
   */
  function isAnchor(item) {
    return route.path === GRAPH_ROUTE_PATH && Boolean(item.path) && item.path === route.query.path
  }

  /**
   * OpenProject #3353: the folder-click counterpart to `graphSidebarBranch()` above. While `/_graph`
   * is open, clicking a POPULATED folder's header must both keep doing its ordinary expand/collapse
   * (`NavSidebarItem.vue`'s `<w-expansion-item>` header never binds `destination()` at all, only
   * `@click.capture` for ctrl/shift) and re-anchor the graph on that folder + its descendants -- but
   * unlike a page item, it must never be treated as navigable to on its own, so this re-anchors
   * directly with `router.replace()` rather than handing back a `{ clickable, onClick }` pair whose
   * caller would bind it in place of the toggle.
   *
   * Same guard `graphSidebarBranch()` uses -- no-ops outside `/_graph`, for an item with no `path`,
   * or when this folder is already the active anchor -- so repeatedly clicking an already-anchored
   * folder just keeps toggling it open and closed without spamming `router.replace()` or restarting
   * the graph's re-center animation on every click.
   *
   * Called directly from `NavSidebarItem.vue#handleHeaderClick()`'s plain-click fallthrough, not
   * wired through `destination()`: an EMPTY folder (no `children`) needs no equivalent here, since it
   * renders through the leaf branch and already reaches `graphSidebarBranch()` via `destination()` --
   * that function does not distinguish a folder's `item.path` from a page's.
   */
  function reanchorGraphOnFolder(item) {
    if (route.path !== GRAPH_ROUTE_PATH || !item.path || isAnchor(item)) {
      return
    }
    router.replace({ path: GRAPH_ROUTE_PATH, query: { path: item.path } })
  }

  return { destination, isCurrent, isAnchor, containsCurrent, reanchorGraphOnFolder }
}

/**
 * Every folder id in the given nav tree, walked recursively regardless of current expand/collapse
 * state (OpenProject #2848) -- a folder here means "renders as a `w-expansion-item`", i.e. carries
 * at least one child (`NavSidebarItem.vue`'s own `v-if`), not merely `item.isFolder`: an empty or
 * boundary folder has nothing to expand or collapse. Plain and store-free, unlike the composable
 * above, since it only ever walks a tree already in hand (`siteStore.nav.items`).
 */
export function folderIds(items) {
  const ids = []
  for (const item of items ?? []) {
    if (item.children?.length > 0) {
      ids.push(item.id, ...folderIds(item.children))
    }
  }
  return ids
}

/**
 * The ids of every ancestor FOLDER of the item `targetId`, outer-to-inner, not including `targetId`
 * itself -- what shift+click isolate (OpenProject #2848/#3062) keeps open alongside the clicked
 * folder while collapsing every other id `folderIds` names. Empty when `targetId` is not found in
 * `items`, or is itself a root-level item with no ancestors.
 */
export function ancestorIds(items, targetId) {
  function walk(list) {
    for (const item of list ?? []) {
      if (item.id === targetId) {
        return []
      }
      if (item.children?.length > 0) {
        const nested = walk(item.children)
        if (nested !== null) {
          return [item.id, ...nested]
        }
      }
    }
    return null
  }
  return walk(items) ?? []
}
