-- Repoint every stored icon reference that still names one of the interface's own former
-- Line Awesome / Material Design Icons defaults at its Tabler equivalent.
--
-- The interface is drawn entirely in Tabler now (`frontend/src/assets/icons.generated.js` holds
-- nothing else), but a page, block or navigation item records the icon it was created with as a
-- string in the database -- so an instance created before the change keeps showing the old glyph
-- next to its title long after the chrome around it has changed hands. This is that data, moved
-- once, using the same name-for-name table the source sweep used.
CREATE TEMPORARY TABLE "cardinal_icon_map" ("from" text PRIMARY KEY, "to" text NOT NULL);--> statement-breakpoint

INSERT INTO "cardinal_icon_map" ("from", "to") VALUES
    ('la:angle-double-left', 'tabler:chevrons-left'),
    ('la:angle-double-right', 'tabler:chevrons-right'),
    ('la:angle-right', 'tabler:chevron-right'),
    ('la:arrow-circle-left', 'tabler:circle-arrow-left'),
    ('la:arrow-circle-right', 'tabler:circle-arrow-right'),
    ('la:arrow-down', 'tabler:arrow-down'),
    ('la:arrow-left', 'tabler:arrow-left'),
    ('la:arrow-right', 'tabler:arrow-right'),
    ('la:arrow-up', 'tabler:arrow-up'),
    ('la:asterisk', 'tabler:asterisk'),
    ('la:ban', 'tabler:ban'),
    ('la:bars', 'tabler:menu-2'),
    ('la:bell', 'tabler:bell'),
    ('la:bolt', 'tabler:bolt'),
    ('la:book', 'tabler:book'),
    ('la:box', 'tabler:box'),
    ('la:broadcast-tower', 'tabler:broadcast'),
    ('la:broom', 'tabler:wash-machine'),
    ('la:calendar', 'tabler:calendar'),
    ('la:caret-square-right', 'tabler:square-chevron-right'),
    ('la:chalkboard', 'tabler:presentation'),
    ('la:chart-area', 'tabler:chart-area'),
    ('la:check', 'tabler:check'),
    ('la:check-circle', 'tabler:circle-check'),
    ('la:check-double', 'tabler:checks'),
    ('la:check-square', 'tabler:checkbox'),
    ('la:circle', 'tabler:circle'),
    ('la:clipboard', 'tabler:clipboard'),
    ('la:clipboard-check', 'tabler:clipboard-check'),
    ('la:clipboard-list', 'tabler:clipboard-list'),
    ('la:clock', 'tabler:clock'),
    ('la:cloud-upload-alt', 'tabler:cloud-upload'),
    ('la:code', 'tabler:code'),
    ('la:code-branch', 'tabler:git-branch'),
    ('la:cog', 'tabler:settings'),
    ('la:comments', 'tabler:messages'),
    ('la:copy', 'tabler:copy'),
    ('la:dharmachakra', 'tabler:steering-wheel'),
    ('la:dice-d6', 'tabler:cube'),
    ('la:directions', 'tabler:directions'),
    ('la:download', 'tabler:download'),
    ('la:edit', 'tabler:edit'),
    ('la:ellipsis-h', 'tabler:dots'),
    ('la:ellipsis-v', 'tabler:dots-vertical'),
    ('la:envelope', 'tabler:mail'),
    ('la:envelope-open-text', 'tabler:mail-opened'),
    ('la:exclamation-triangle', 'tabler:alert-triangle'),
    ('la:external-link-alt', 'tabler:external-link'),
    ('la:external-link-square-alt', 'tabler:external-link'),
    ('la:eye', 'tabler:eye'),
    ('la:file', 'tabler:file'),
    ('la:file-alt', 'tabler:file-text'),
    ('la:file-export', 'tabler:file-export'),
    ('la:file-image', 'tabler:file-type-jpg'),
    ('la:file-import', 'tabler:file-import'),
    ('la:file-invoice', 'tabler:file-invoice'),
    ('la:file-pdf', 'tabler:file-type-pdf'),
    ('la:fill', 'tabler:paint'),
    ('la:fingerprint', 'tabler:fingerprint'),
    ('la:folder-open', 'tabler:folder-open'),
    ('la:frog', 'tabler:fish'),
    ('la:globe', 'tabler:world'),
    ('la:hashtag', 'tabler:hash'),
    ('la:heading', 'tabler:heading'),
    ('la:heart', 'tabler:heart'),
    ('la:history', 'tabler:history'),
    ('la:home', 'tabler:home'),
    ('la:icons', 'tabler:icons'),
    ('la:id-card', 'tabler:id'),
    ('la:image', 'tabler:photo'),
    ('la:inbox', 'tabler:inbox'),
    ('la:info-circle', 'tabler:info-circle'),
    ('la:key', 'tabler:key'),
    ('la:language', 'tabler:language'),
    ('la:layer-group', 'tabler:stack-2'),
    ('la:leaf', 'tabler:leaf'),
    ('la:life-ring', 'tabler:lifebuoy'),
    ('la:link', 'tabler:link'),
    ('la:list', 'tabler:list'),
    ('la:list-alt', 'tabler:list-details'),
    ('la:lock', 'tabler:lock'),
    ('la:lock-open', 'tabler:lock-open'),
    ('la:magic', 'tabler:wand'),
    ('la:markdown', 'tabler:markdown'),
    ('la:microchip', 'tabler:cpu'),
    ('la:minus', 'tabler:minus'),
    ('la:mountain', 'tabler:mountain'),
    ('la:otter', 'tabler:paw'),
    ('la:paper-plane', 'tabler:send'),
    ('la:pen', 'tabler:pencil'),
    ('la:pen-nib', 'tabler:ballpen'),
    ('la:play', 'tabler:player-play'),
    ('la:plug', 'tabler:plug'),
    ('la:plus', 'tabler:plus'),
    ('la:plus-circle', 'tabler:plus'),
    ('la:power-off', 'tabler:power'),
    ('la:print', 'tabler:printer'),
    ('la:question-circle', 'tabler:help-circle'),
    ('la:redo', 'tabler:arrow-forward-up'),
    ('la:redo-alt', 'tabler:refresh'),
    ('la:ruler-vertical', 'tabler:ruler-2'),
    ('la:search', 'tabler:search'),
    ('la:server', 'tabler:server'),
    ('la:share', 'tabler:share'),
    ('la:sign-in-alt', 'tabler:login'),
    ('la:sign-out-alt', 'tabler:logout'),
    ('la:sitemap', 'tabler:sitemap'),
    ('la:snowflake', 'tabler:snowflake'),
    ('la:sort-amount-down', 'tabler:sort-descending'),
    ('la:square', 'tabler:square'),
    ('la:square-full', 'tabler:square'),
    ('la:stop', 'tabler:player-stop'),
    ('la:stream', 'tabler:timeline'),
    ('la:sun', 'tabler:sun'),
    ('la:sync-alt', 'tabler:refresh'),
    ('la:tags', 'tabler:tags'),
    ('la:tasks', 'tabler:list-check'),
    ('la:terminal', 'tabler:terminal-2'),
    ('la:th-list', 'tabler:layout-list'),
    ('la:times', 'tabler:x'),
    ('la:times-circle', 'tabler:circle-x'),
    ('la:tools', 'tabler:tool'),
    ('la:traffic-light', 'tabler:traffic-lights'),
    ('la:trash', 'tabler:trash'),
    ('la:undo', 'tabler:arrow-back-up'),
    ('la:undo-alt', 'tabler:arrow-back-up'),
    ('la:unlink', 'tabler:unlink'),
    ('la:upload', 'tabler:upload'),
    ('la:user', 'tabler:user'),
    ('la:user-alt', 'tabler:user'),
    ('la:user-circle', 'tabler:user-circle'),
    ('la:user-cog', 'tabler:user-cog'),
    ('la:user-friends', 'tabler:users'),
    ('la:user-minus', 'tabler:user-minus'),
    ('la:user-plus', 'tabler:user-plus'),
    ('la:users', 'tabler:users'),
    ('la:window-close', 'tabler:square-x'),
    ('mdi:account-edit', 'tabler:user-edit'),
    ('mdi:alert', 'tabler:alert-triangle'),
    ('mdi:alert-box', 'tabler:alert-square'),
    ('mdi:alert-circle', 'tabler:alert-circle'),
    ('mdi:alpha-a-box-outline', 'tabler:square-letter-a'),
    ('mdi:arrow-right', 'tabler:arrow-right'),
    ('mdi:arrow-vertical-lock', 'tabler:arrows-vertical'),
    ('mdi:basketball', 'tabler:ball-basketball'),
    ('mdi:bell', 'tabler:bell'),
    ('mdi:bell-off-outline', 'tabler:bell-off'),
    ('mdi:bell-outline', 'tabler:bell'),
    ('mdi:book', 'tabler:book'),
    ('mdi:book-open-page-variant-outline', 'tabler:book-2'),
    ('mdi:book-plus', 'tabler:book-upload'),
    ('mdi:car', 'tabler:car'),
    ('mdi:check', 'tabler:check'),
    ('mdi:check-circle', 'tabler:circle-check'),
    ('mdi:checkbox-blank-circle-outline', 'tabler:circle'),
    ('mdi:checkbox-blank-outline', 'tabler:square'),
    ('mdi:checkbox-marked-circle-outline', 'tabler:circle-check'),
    ('mdi:checkbox-outline', 'tabler:checkbox'),
    ('mdi:chevron-down', 'tabler:chevron-down'),
    ('mdi:chevron-left', 'tabler:chevron-left'),
    ('mdi:chevron-right', 'tabler:chevron-right'),
    ('mdi:clipboard-text-outline', 'tabler:clipboard-text'),
    ('mdi:clock-outline', 'tabler:clock'),
    ('mdi:close', 'tabler:x'),
    ('mdi:close-box', 'tabler:square-x'),
    ('mdi:code-json', 'tabler:json'),
    ('mdi:code-tags', 'tabler:code'),
    ('mdi:cog', 'tabler:settings'),
    ('mdi:crop-square', 'tabler:square'),
    ('mdi:database-refresh', 'tabler:database-cog'),
    ('mdi:dog', 'tabler:dog'),
    ('mdi:drag-horizontal', 'tabler:grip-horizontal'),
    ('mdi:emoticon-outline', 'tabler:mood-smile'),
    ('mdi:emoticon-plus-outline', 'tabler:mood-plus'),
    ('mdi:exclamation', 'tabler:exclamation-mark'),
    ('mdi:eye', 'tabler:eye'),
    ('mdi:eye-off', 'tabler:eye-off'),
    ('mdi:eye-off-outline', 'tabler:eye-off'),
    ('mdi:file', 'tabler:file'),
    ('mdi:file-document-outline', 'tabler:file-text'),
    ('mdi:file-tree', 'tabler:binary-tree'),
    ('mdi:flag-outline', 'tabler:flag'),
    ('mdi:folder', 'tabler:folder'),
    ('mdi:food-apple-outline', 'tabler:apple'),
    ('mdi:format-align-center', 'tabler:align-center'),
    ('mdi:format-align-justify', 'tabler:align-justified'),
    ('mdi:format-align-left', 'tabler:align-left'),
    ('mdi:format-align-right', 'tabler:align-right'),
    ('mdi:format-bold', 'tabler:bold'),
    ('mdi:format-clear', 'tabler:clear-formatting'),
    ('mdi:format-font', 'tabler:typography'),
    ('mdi:format-header-1', 'tabler:h-1'),
    ('mdi:format-header-2', 'tabler:h-2'),
    ('mdi:format-header-3', 'tabler:h-3'),
    ('mdi:format-header-4', 'tabler:h-4'),
    ('mdi:format-header-5', 'tabler:h-5'),
    ('mdi:format-header-6', 'tabler:h-6'),
    ('mdi:format-header-pound', 'tabler:heading'),
    ('mdi:format-indent-decrease', 'tabler:indent-decrease'),
    ('mdi:format-indent-increase', 'tabler:indent-increase'),
    ('mdi:format-italic', 'tabler:italic'),
    ('mdi:format-list-bulleted', 'tabler:list'),
    ('mdi:format-list-checks', 'tabler:list-check'),
    ('mdi:format-list-numbered', 'tabler:list-numbers'),
    ('mdi:format-page-break', 'tabler:page-break'),
    ('mdi:format-paragraph', 'tabler:pilcrow'),
    ('mdi:format-quote-close', 'tabler:quote'),
    ('mdi:format-quote-open', 'tabler:blockquote'),
    ('mdi:format-strikethrough', 'tabler:strikethrough'),
    ('mdi:format-subscript', 'tabler:subscript'),
    ('mdi:format-superscript', 'tabler:superscript'),
    ('mdi:graph-outline', 'tabler:topology-star-3'),
    ('mdi:hand-wave-outline', 'tabler:hand-move'),
    ('mdi:help', 'tabler:help'),
    ('mdi:home', 'tabler:home'),
    ('mdi:image-plus', 'tabler:photo-plus'),
    ('mdi:image-plus-outline', 'tabler:photo-plus'),
    ('mdi:image-sync-outline', 'tabler:photo-cog'),
    ('mdi:import', 'tabler:file-import'),
    ('mdi:inbox-full', 'tabler:inbox'),
    ('mdi:information', 'tabler:info-circle'),
    ('mdi:information-box', 'tabler:square-rounded-letter-i'),
    ('mdi:keyboard-variant', 'tabler:keyboard'),
    ('mdi:language-html5', 'tabler:brand-html5'),
    ('mdi:language-python', 'tabler:brand-python'),
    ('mdi:letter-a-box', 'tabler:square-letter-a'),
    ('mdi:letter-b-box', 'tabler:square-letter-b'),
    ('mdi:lightbulb-outline', 'tabler:bulb'),
    ('mdi:line-scan', 'tabler:scan'),
    ('mdi:link', 'tabler:link'),
    ('mdi:link-variant', 'tabler:link'),
    ('mdi:link-variant-plus', 'tabler:link-plus'),
    ('mdi:logout', 'tabler:logout'),
    ('mdi:marker', 'tabler:highlight'),
    ('mdi:marker-cancel', 'tabler:highlight-off'),
    ('mdi:menu-down', 'tabler:chevron-down'),
    ('mdi:message-alert', 'tabler:message-exclamation'),
    ('mdi:minus', 'tabler:minus'),
    ('mdi:minus-box-outline', 'tabler:square-minus'),
    ('mdi:palette', 'tabler:palette'),
    ('mdi:pencil', 'tabler:pencil'),
    ('mdi:percent-outline', 'tabler:percentage'),
    ('mdi:playlist-edit', 'tabler:list-details'),
    ('mdi:redo-variant', 'tabler:arrow-forward-up'),
    ('mdi:restore', 'tabler:restore'),
    ('mdi:seed-plus-outline', 'tabler:seeding'),
    ('mdi:source-branch-sync', 'tabler:git-branch'),
    ('mdi:star', 'tabler:star'),
    ('mdi:tab-plus', 'tabler:browser-plus'),
    ('mdi:table', 'tabler:table'),
    ('mdi:table-column', 'tabler:table-column'),
    ('mdi:table-column-plus-after', 'tabler:column-insert-right'),
    ('mdi:table-column-plus-before', 'tabler:column-insert-left'),
    ('mdi:table-column-remove', 'tabler:column-remove'),
    ('mdi:table-heart', 'tabler:table-heart'),
    ('mdi:table-large-plus', 'tabler:table-plus'),
    ('mdi:table-large-remove', 'tabler:table-minus'),
    ('mdi:table-merge-cells', 'tabler:layout-board'),
    ('mdi:table-row', 'tabler:table-row'),
    ('mdi:table-row-plus-after', 'tabler:row-insert-bottom'),
    ('mdi:table-row-plus-before', 'tabler:row-insert-top'),
    ('mdi:table-row-remove', 'tabler:row-remove'),
    ('mdi:table-split-cell', 'tabler:layout-columns'),
    ('mdi:text-box-outline', 'tabler:file-text'),
    ('mdi:toy-brick-plus', 'tabler:puzzle'),
    ('mdi:transfer-down', 'tabler:arrow-bar-down'),
    ('mdi:transfer-up', 'tabler:arrow-bar-up'),
    ('mdi:tune-variant', 'tabler:adjustments'),
    ('mdi:undo-variant', 'tabler:arrow-back-up'),
    ('mdi:view-split-vertical', 'tabler:layout-columns'),
    ('mdi:wifi-off', 'tabler:wifi-off');--> statement-breakpoint

UPDATE "pages" SET icon = m."to" FROM "cardinal_icon_map" m WHERE "pages".icon = m."from";--> statement-breakpoint

UPDATE "blocks" SET icon = m."to" FROM "cardinal_icon_map" m WHERE "blocks".icon = m."from";--> statement-breakpoint

-- Navigation items are a jsonb array of objects, each of which may carry an `icon`. Rebuilt element
-- by element so an item with no icon, or one naming something outside the table, is copied through
-- untouched.
UPDATE "navigation" SET items = rebuilt.items
FROM (
  SELECT n.id,
         COALESCE(jsonb_agg(
           CASE WHEN m."to" IS NULL THEN item ELSE jsonb_set(item, '{icon}', to_jsonb(m."to")) END
           ORDER BY ord
         ), '[]'::jsonb) AS items
  FROM "navigation" n
  CROSS JOIN LATERAL jsonb_array_elements(n.items) WITH ORDINALITY AS e(item, ord)
  LEFT JOIN "cardinal_icon_map" m ON m."from" = e.item ->> 'icon'
  GROUP BY n.id
) rebuilt
WHERE "navigation".id = rebuilt.id;--> statement-breakpoint

-- Tabler is what the interface itself is drawn in, so an instance that predates it still has to be
-- offered the set in the icon picker. `ON CONFLICT DO NOTHING` leaves an administrator who already
-- added it (and any name they gave it) alone.
INSERT INTO "iconSets" ("prefix", "name") VALUES ('tabler', 'Tabler Icons') ON CONFLICT DO NOTHING;
