import path from 'node:path'
import { asc, eq } from 'drizzle-orm'
import { isSafePattern } from 'redos-detector'
import { syncRevocableGroupIds } from '../helpers/groupSync.ts'
import { maskSensitiveConfig } from '../helpers/moduleProps.ts'
import {
  mergeModuleConfig,
  readModuleDefinitions,
  validateModuleConfig
} from '../helpers/moduleRegistry.ts'
import { authentication as authenticationTable, groups as groupsTable } from '../db/schema.ts'
import type { ModuleProp } from '../helpers/moduleProps.ts'
import type { SystemIds } from './types.ts'

export interface GroupSyncWarningStrategy {
  id: string
  displayName: string
}

export interface GroupSyncWarning {
  groupId: string
  strategies: GroupSyncWarningStrategy[]
}

export interface AuthModule {
  key: string
  title: string
  description: string
  logo?: string
  icon?: string
  color?: string
  vendor?: string
  website?: string
  isAvailable: boolean
  useForm: boolean
  /**
   * Only meaningful when `useForm` is true: whether this module's `authenticate()` can throw
   * `ProvisionableLoginError` and so reach the find-or-create-by-email path. Local cannot — it
   * resolves against its own stored password hash and produces no external profile.
   */
  provisionable?: boolean
  usernameType: string
  props: Record<string, ModuleProp>
  refs?: Record<string, { title?: string; hint?: string; icon?: string; value: string }>
}

/**
 * The framework owns these values rather than each module inventing them: generated once per login,
 * kept on the session, and checked when the provider comes back — which is what makes the answer
 * belong to the browser that started the flow. A module with no use for `nonce` or `codeVerifier`
 * ignores them.
 */
export interface AuthFlow {
  /** Registered with the provider by the administrator. */
  redirectUri: string
  /**
   * Ties the callback back to the browser that started this login. Only OAuth2/OIDC define a `state`
   * parameter, so each protocol threads it differently: OAuth2/OIDC round-trip the native query
   * parameter, SAML carries it in `RelayState`, and CAS — which defines neither — appends it to the
   * registered `service` URL itself and reads it back off the GET callback.
   */
  state: string
  nonce: string
  codeVerifier: string
  /**
   * SAML only: the `ID` on the outbound `AuthnRequest`. Generated by the framework rather than by
   * `@node-saml/node-saml`, so it can be stored on `req.session.authFlow` before the request is built
   * and read back once the identity provider answers — that round trip is what makes
   * `validateInResponseTo` enforceable at all.
   */
  authnRequestId?: string
}

export interface AuthFlowCallback extends AuthFlow {
  /** As it arrived, query string included — what an OIDC library validates against. */
  currentUrl: string
  code?: string
  /** CAS's equivalent of `code`. Absent for every other protocol. */
  ticket?: string
  /**
   * The parsed form-encoded body, for a provider that answers with a POST rather than a redirect —
   * SAML's `SAMLResponse` and `RelayState` arrive this way. Absent on a GET callback.
   */
  body?: Record<string, any>
}

/**
 * `id` is the provider's own identifier for the account and never changes — binding an existing
 * account to it, and re-checking it on every later login, is what keeps `email` from standing in as
 * proof of identity: a provider that can be made to assert an arbitrary address would otherwise be
 * able to sign in as whichever account already used it. A module must not return an address it has
 * not established belongs to the person.
 */
export interface ProviderProfile {
  id: string
  email: string
  name: string
  /** Absent or '' means the provider did not say. */
  firstName?: string
  lastName?: string
  /**
   * For a strategy configured with `mapGroups: true`. `undefined` and `[]` are different answers:
   * absent means the module did not look, and leaves wiki-side group membership untouched.
   */
  groups?: string[]
  /** Absent means the provider did not say — never fabricate one. */
  picture?: string
}

/**
 * Every module that issues the separated halves spreads this rather than assembling the pair itself,
 * so all agree on two decisions: only a genuine string counts, since coercing a structured claim
 * would invent a surname out of `[object Object]`; and an empty answer leaves the key off entirely.
 *
 * Neither half is ever derived from the other or from `name` — a first name with no surname is the
 * mononym case. Splitting a single display name into halves is a per-module fallback.
 */
export function providerNameHalves(
  firstName: unknown,
  lastName: unknown
): { firstName?: string; lastName?: string } {
  const first = typeof firstName === 'string' ? firstName.trim() : ''
  const last = typeof lastName === 'string' ? lastName.trim() : ''
  return {
    ...(first ? { firstName: first } : {}),
    ...(last ? { lastName: last } : {})
  }
}

/**
 * Thrown by a form-based module's `authenticate()` when the credentials checked out at the provider
 * but no local account matches yet. A redirect-based provider goes through `loginWithProvider()`,
 * which finds-or-creates the account itself; a form-based one is called straight from `login()` and
 * has no other way to hand back "this person is real, here is who they are, but there is no account
 * for them yet".
 */
export class ProvisionableLoginError extends Error {
  profile: ProviderProfile

  constructor(profile: ProviderProfile) {
    super('ERR_USER_NOT_FOUND_PROVISIONABLE')
    this.name = 'ProvisionableLoginError'
    this.profile = profile
  }
}

export interface AuthStrategy {
  id: string
  module: string
  displayName: string
  isEnabled: boolean
  /** Only ever enforced for a form-based module -- see `models/login.ts#register()`. */
  selfRegistration: boolean
  /** Only ever enforced for a redirect-based module -- see `models/login.ts`'s provider login. */
  autoProvision: boolean
  allowedEmailRegex: string
  /**
   * Matched case-insensitively, stored already normalized by `createStrategy`/`updateStrategy`. Only
   * ever enforced for local self-registration -- unlike `allowedEmailRegex` above, this does not gate
   * provider auto-provisioning. Empty means unrestricted; both may be set on the same strategy.
   */
  allowedEmailDomains: string[]
  autoEnrollGroups: string[]
  /**
   * An existing account is only ever claimed by a provider login when this is on for that strategy —
   * otherwise a matching email address with no stored link is refused rather than silently bound.
   */
  trustEmailForLinking: boolean
  /** Groups `syncProviderGroups()` may grant/revoke. Empty means none, not all. */
  mappableGroups: string[]
  config: Record<string, any>
}

const LOCAL_MODULE = 'local'

/** A bare domain -- no `@`, no scheme, no path. */
const DOMAIN_PATTERN =
  /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$/i

/**
 * Case is folded at write time rather than left to whatever later reads the column, so every
 * consumer sees the one canonical form.
 */
function normalizeEmailDomains(domains: string[]): string[] {
  const seen = new Set<string>()
  for (const raw of domains) {
    const domain = raw.trim().toLowerCase()
    if (domain) {
      seen.add(domain)
    }
  }
  return [...seen]
}

/**
 * Not merely "a local strategy": every account's password is stored under this exact strategy ID, so
 * it is the one that cannot be disabled or deleted. A second instance of the local module holds no
 * credentials and is as disposable as any other strategy.
 */
function isBuiltInLocal(id: string): boolean {
  return id === CARDINAL.data.systemIds.localAuthId
}

class Authentication {
  async getStrategies({ enabledOnly = false }: { enabledOnly?: boolean } = {}) {
    return CARDINAL.db
      .select()
      .from(authenticationTable)
      .where(enabledOnly ? eq(authenticationTable.isEnabled, true) : undefined)
  }

  getModules(): AuthModule[] {
    return [...((CARDINAL.data.authentication ?? []) as AuthModule[])].sort((a, b) =>
      a.key === LOCAL_MODULE ? -1 : b.key === LOCAL_MODULE ? 1 : a.title.localeCompare(b.title)
    )
  }

  getModule(key: string): AuthModule | null {
    return this.getModules().find((m) => m.key === key) ?? null
  }

  /**
   * Config values are completed from the module's declared defaults, so a prop added to a module
   * after a strategy was configured comes back with its default rather than as a missing key.
   *
   * @param opts.mask Replace a `sensitive` prop's stored value with a mask before returning it.
   *   Defaults to false: `updateStrategy()`'s own merge reads through this method too, and needs the
   *   real values to preserve an untouched secret correctly. Only an admin-facing read that
   *   serializes `config` straight into an HTTP response should pass `{ mask: true }`.
   */
  async getActiveStrategies({ mask = false }: { mask?: boolean } = {}): Promise<AuthStrategy[]> {
    const strategies = await CARDINAL.db
      .select()
      .from(authenticationTable)
      .orderBy(asc(authenticationTable.displayName))
    return strategies
      .map((stg) => {
        const config = this.buildConfig(stg.module, {}, stg.config as Record<string, any>)
        return {
          ...stg,
          allowedEmailDomains: stg.allowedEmailDomains ?? [],
          autoEnrollGroups: stg.autoEnrollGroups ?? [],
          mappableGroups: stg.mappableGroups ?? [],
          config: mask
            ? maskSensitiveConfig(this.getModule(stg.module)?.props ?? {}, config)
            : config
        }
      })
      .sort((a, b) => (isBuiltInLocal(a.id) ? -1 : isBuiltInLocal(b.id) ? 1 : 0))
  }

  async getStrategyById(id: string, opts?: { mask?: boolean }): Promise<AuthStrategy | null> {
    return (await this.getActiveStrategies(opts)).find((stg) => stg.id === id) ?? null
  }

  /**
   * One entry per group at risk of `models/login.ts#syncProviderGroups()` silently reverting a manual
   * grant on the account's next login, naming every strategy that could do the reverting.
   *
   * Carries no secrets — only group ids and strategy display names — unlike `getActiveStrategies()`,
   * so it is reachable by a `manage:users`/`manage:groups` holder, not only `manage:system`.
   */
  async getGroupSyncWarnings(): Promise<GroupSyncWarning[]> {
    const strategies = await this.getActiveStrategies()
    const mapping = strategies.filter((stg) => stg.isEnabled && stg.config?.mapGroups)
    if (mapping.length < 1) {
      return []
    }
    const guestsGroupId = CARDINAL.data.systemIds.guestsGroupId
    const rootAdminGroupId = CARDINAL.config.auth.rootAdminGroupId
    const systemGroupIds = await CARDINAL.models.groups.systemGroupIds()

    const byGroup = new Map<string, GroupSyncWarningStrategy[]>()
    for (const stg of mapping) {
      for (const groupId of syncRevocableGroupIds(stg, {
        guestsGroupId,
        rootAdminGroupId,
        systemGroupIds
      })) {
        const strategiesForGroup = byGroup.get(groupId) ?? []
        strategiesForGroup.push({ id: stg.id, displayName: stg.displayName })
        byGroup.set(groupId, strategiesForGroup)
      }
    }
    return [...byGroup.entries()].map(([groupId, strategiesForGroup]) => ({
      groupId,
      strategies: strategiesForGroup
    }))
  }

  /**
   * Applies the same `isVisible ?? false` fallback the public strategy listing does. A strategy no
   * site marks visible is absent from the map rather than present with a zero count.
   */
  async getVisibleSiteCounts(): Promise<Record<string, number>> {
    const counts: Record<string, number> = {}
    for (const site of await CARDINAL.models.sites.getAllSites()) {
      const configured = ((site.config as Record<string, any>)?.authStrategies ?? []) as Array<{
        id: string
        isVisible?: boolean
      }>
      for (const entry of configured) {
        if (entry.isVisible) {
          counts[entry.id] = (counts[entry.id] ?? 0) + 1
        }
      }
    }
    return counts
  }

  buildConfig(
    moduleKey: string,
    incoming: Record<string, any> = {},
    existing: Record<string, any> = {}
  ): Record<string, any> {
    return mergeModuleConfig(this.getModule(moduleKey)?.props ?? {}, incoming, existing)
  }

  /**
   * An unknown key is dropped by `buildConfig` rather than refused here, so a module losing a prop
   * can never make the admin area unable to save.
   */
  validateConfig(moduleKey: string, incoming: Record<string, any> = {}): string | null {
    return validateModuleConfig(this.getModule(moduleKey)?.props ?? {}, incoming)
  }

  /**
   * @param strategy The values as they will end up stored — already merged with the current ones
   */
  async validateStrategy(strategy: {
    id?: string
    module: string
    displayName?: string
    isEnabled?: boolean
    allowedEmailRegex?: string
    allowedEmailDomains?: string[]
    autoEnrollGroups?: string[]
    mappableGroups?: string[]
  }): Promise<string | null> {
    if (strategy.displayName !== undefined && strategy.displayName.trim().length < 1) {
      return 'The display name cannot be empty.'
    }
    if (strategy.id && isBuiltInLocal(strategy.id) && strategy.isEnabled === false) {
      return 'The built-in local strategy cannot be disabled, as it would leave no way to log in.'
    }
    if (strategy.allowedEmailRegex) {
      try {
        new RegExp(strategy.allowedEmailRegex)
      } catch (err: any) {
        return `The allowed email pattern is not a valid regular expression: ${err.message}`
      }
      // -> Syntax-valid is not the same as safe: `models/login.ts#assertAllowedProviderEmail` runs
      //    this pattern fresh on every login attempt against the strategy, so a catastrophic-
      //    backtracking pattern would hang the event loop on every one of them. The runtime guard in
      //    `helpers/safeRegexTest.ts` is defense in depth for an already-stored pattern, not a
      //    substitute for refusing a bad one here.
      if (!isSafePattern(strategy.allowedEmailRegex).safe) {
        return 'The allowed email pattern is vulnerable to catastrophic backtracking (ReDoS) and cannot be saved. Simplify it -- avoid nested or overlapping quantifiers such as `(a+)+` or `(a|a)+`.'
      }
    }
    if (strategy.allowedEmailDomains) {
      const invalidDomain = normalizeEmailDomains(strategy.allowedEmailDomains).find(
        (domain) => !DOMAIN_PATTERN.test(domain)
      )
      if (invalidDomain) {
        return `"${invalidDomain}" is not a valid domain.`
      }
    }
    if (strategy.autoEnrollGroups && strategy.autoEnrollGroups.length > 0) {
      if (strategy.autoEnrollGroups.includes(CARDINAL.data.systemIds.guestsGroupId)) {
        return 'The guests group cannot be used for auto-enrollment.'
      }
      const existing = await CARDINAL.db.select({ id: groupsTable.id }).from(groupsTable)
      const existingIds = existing.map((g) => g.id)
      const unknown = strategy.autoEnrollGroups.find((id) => !existingIds.includes(id))
      if (unknown) {
        return `Group ${unknown} does not exist.`
      }
    }
    if (strategy.mappableGroups && strategy.mappableGroups.length > 0) {
      if (strategy.mappableGroups.includes(CARDINAL.data.systemIds.guestsGroupId)) {
        return 'The guests group cannot be mapped from a provider.'
      }
      const existing = await CARDINAL.db.select({ id: groupsTable.id }).from(groupsTable)
      const existingIds = existing.map((g) => g.id)
      const unknown = strategy.mappableGroups.find((id) => !existingIds.includes(id))
      if (unknown) {
        return `Group ${unknown} does not exist.`
      }
    }
    return null
  }

  async createStrategy(values: {
    module: string
    displayName?: string
    isEnabled?: boolean
    selfRegistration?: boolean
    autoProvision?: boolean
    allowedEmailRegex?: string
    allowedEmailDomains?: string[]
    autoEnrollGroups?: string[]
    trustEmailForLinking?: boolean
    mappableGroups?: string[]
    config?: Record<string, any>
  }): Promise<string> {
    const mod = this.getModule(values.module)!
    const result = await CARDINAL.db
      .insert(authenticationTable)
      .values({
        module: values.module,
        displayName: values.displayName?.trim() || mod.title,
        isEnabled: values.isEnabled ?? true,
        selfRegistration: values.selfRegistration ?? false,
        autoProvision: values.autoProvision ?? false,
        allowedEmailRegex: values.allowedEmailRegex ?? '',
        allowedEmailDomains: normalizeEmailDomains(values.allowedEmailDomains ?? []),
        autoEnrollGroups: values.autoEnrollGroups ?? [],
        trustEmailForLinking: values.trustEmailForLinking ?? false,
        mappableGroups: values.mappableGroups ?? [],
        config: this.buildConfig(values.module, values.config)
      })
      .returning({ id: authenticationTable.id })

    const newId = result[0].id

    // -> Left absent, a site's per-strategy entry falls back to `isVisible: false`, so a new strategy
    //    would show up nowhere until an admin visited every site's Login settings. Read the full
    //    array, append, write the whole array back -- `updateSite()` replaces an array wholesale
    //    rather than merging it index-wise.
    for (const site of await CARDINAL.models.sites.getAllSites()) {
      const configured = ((site.config as Record<string, any>)?.authStrategies ?? []) as Array<{
        id: string
        order?: number
        isVisible?: boolean
      }>
      const nextOrder = configured.reduce((max, s) => Math.max(max, s.order ?? 0), -1) + 1
      await CARDINAL.models.sites.updateSite(site.id, {
        config: {
          authStrategies: [...configured, { id: newId, order: nextOrder, isVisible: true }]
        }
      })
    }

    await this.activateStrategies()
    return newId
  }

  async updateStrategy(
    id: string,
    patch: {
      displayName?: string
      isEnabled?: boolean
      selfRegistration?: boolean
      autoProvision?: boolean
      allowedEmailRegex?: string
      allowedEmailDomains?: string[]
      autoEnrollGroups?: string[]
      trustEmailForLinking?: boolean
      mappableGroups?: string[]
      config?: Record<string, any>
    }
  ): Promise<boolean> {
    const current = await this.getStrategyById(id)
    if (!current) {
      return false
    }

    const values: Partial<typeof authenticationTable.$inferInsert> = {}
    if (patch.displayName !== undefined) {
      values.displayName = patch.displayName.trim()
    }
    if (patch.isEnabled !== undefined) {
      values.isEnabled = patch.isEnabled
    }
    if (patch.selfRegistration !== undefined) {
      values.selfRegistration = patch.selfRegistration
    }
    if (patch.autoProvision !== undefined) {
      values.autoProvision = patch.autoProvision
    }
    if (patch.allowedEmailRegex !== undefined) {
      values.allowedEmailRegex = patch.allowedEmailRegex
    }
    if (patch.allowedEmailDomains !== undefined) {
      values.allowedEmailDomains = normalizeEmailDomains(patch.allowedEmailDomains)
    }
    if (patch.autoEnrollGroups !== undefined) {
      values.autoEnrollGroups = patch.autoEnrollGroups
    }
    if (patch.trustEmailForLinking !== undefined) {
      values.trustEmailForLinking = patch.trustEmailForLinking
    }
    if (patch.mappableGroups !== undefined) {
      values.mappableGroups = patch.mappableGroups
    }
    if (patch.config !== undefined) {
      values.config = this.buildConfig(current.module, patch.config, current.config)
    }
    if (Object.keys(values).length < 1) {
      return false
    }

    const result = await CARDINAL.db
      .update(authenticationTable)
      .set(values)
      .where(eq(authenticationTable.id, id))
    if ((result.rowCount ?? 0) < 1) {
      return false
    }

    await this.activateStrategies()
    return true
  }

  async deleteStrategy(id: string): Promise<boolean> {
    const result = await CARDINAL.db
      .delete(authenticationTable)
      .where(eq(authenticationTable.id, id))
    if ((result.rowCount ?? 0) < 1) {
      return false
    }

    // -> Sites keep their own ordered list of strategy IDs, which would otherwise keep a dangling one
    for (const site of await CARDINAL.models.sites.getAllSites()) {
      const configured = ((site.config as Record<string, any>)?.authStrategies ?? []) as Array<{
        id: string
      }>
      if (configured.some((s) => s.id === id)) {
        await CARDINAL.models.sites.updateSite(site.id, {
          config: { authStrategies: configured.filter((s) => s.id !== id) }
        })
      }
    }

    await this.activateStrategies()
    return true
  }

  async refreshStrategiesFromDisk(): Promise<void> {
    // -> Emptied before the scan, not merely reassigned on success: `base.yml` declares no
    //    `authentication` key, and the login/registration and strategy-listing paths all call
    //    `CARDINAL.data.authentication.find(...)` unguarded, so a failed scan has to leave them an
    //    empty list to walk rather than `undefined` to throw a 500 on.
    CARDINAL.data.authentication = []
    try {
      // -> A definition on disk this build ships no implementation for must not reach the admin
      //    area's picker.
      CARDINAL.data.authentication = await readModuleDefinitions<AuthModule>(
        path.join(CARDINAL.SERVERPATH, 'modules/authentication'),
        {
          label: 'authentication module',
          parseProps: true,
          skipUnavailable: true,
          logEach: true
        }
      )

      CARDINAL.logger.debug('auth', 'loaded module definitions', {
        modules: CARDINAL.data.authentication.length
      })
    } catch (err: any) {
      CARDINAL.logger.error('auth', 'reading the module definitions failed', { error: err })
    }
  }

  async activateStrategies(): Promise<void> {
    try {
      for (const strKey in CARDINAL.auth.strategies) {
        const strategy = CARDINAL.auth.strategies[strKey] as any
        if (typeof strategy.destroy === 'function') {
          await strategy.destroy()
        }
      }
    } catch (err: any) {
      CARDINAL.logger.warn('auth', 'unloading the active strategies failed', { error: err })
    }
    CARDINAL.auth.strategies = {}

    const enabledStrategies = await this.getStrategies({ enabledOnly: true })
    const enabled: string[] = []
    for (const stg of enabledStrategies) {
      try {
        const StrategyModule = (
          await import(`../modules/authentication/${stg.module}/authentication.ts`)
        ).default
        const strategy = new StrategyModule(stg.id, stg.config)
        CARDINAL.auth.strategies[stg.id] = strategy
        strategy.module = stg.module
        if (typeof strategy.init === 'function') {
          await strategy.init()
        }

        enabled.push(stg.module)
      } catch (err: any) {
        CARDINAL.logger.error('auth', 'enabling the strategy failed', {
          strategy: stg.id,
          module: stg.module,
          error: err
        })
      }
    }
    // -> One line for the whole pass: the module keys are what tell an operator which ways in are
    //    open.
    CARDINAL.logger.info(
      'auth',
      `enabled ${enabled.length} ${enabled.length === 1 ? 'strategy' : 'strategies'}`,
      { keys: enabled.join(', ') }
    )
  }

  async init(ids: SystemIds): Promise<void> {
    await CARDINAL.db.insert(authenticationTable).values({
      id: ids.authModuleId,
      module: 'local',
      isEnabled: true,
      displayName: 'Local Authentication',
      config: {
        emailValidation: true,
        enforceTfa: false
      }
    })
  }
}

export const authentication = new Authentication()
