import path from 'node:path'
import { asc, eq } from 'drizzle-orm'
import { syncRevocableGroupIds } from '../helpers/groupSync.ts'
import { maskSensitiveConfig } from '../helpers/moduleProps.ts'
import {
  mergeModuleConfig,
  readModuleDefinitions,
  validateModuleConfig
} from '../helpers/moduleRegistry.ts'
import { authentication as authenticationTable, groups as groupsTable } from '../db/schema.ts'
import type { ModuleProp } from '../helpers/moduleProps.ts'
import type { SystemIds } from './types.ts'

/** One enabled, group-mapping strategy that could revoke a given group on the account's next login. */
export interface GroupSyncWarningStrategy {
  id: string
  displayName: string
}

/** One group currently at risk of a `mapGroups` strategy silently reverting a manual grant. */
export interface GroupSyncWarning {
  groupId: string
  strategies: GroupSyncWarningStrategy[]
}

/** An authentication module, as declared by its `definition.yml`. */
export interface AuthModule {
  key: string
  title: string
  description: string
  logo?: string
  icon?: string
  color?: string
  vendor?: string
  website?: string
  isAvailable: boolean
  useForm: boolean
  /**
   * Only meaningful when `useForm` is true: whether this module's own `authenticate()` can throw
   * `ProvisionableLoginError` and so dispatch through the same find-or-create-by-email path a
   * redirect-based provider uses (see `models/login.ts`'s catch of it, and `ProvisionableLoginError`
   * below). LDAP declares this; Local does not — it resolves directly against its own stored
   * password hash and never produces a provisionable external profile. This is what the admin UI
   * gates the `trustEmailForLinking` toggle on for a form-based module.
   */
  provisionable?: boolean
  usernameType: string
  props: Record<string, ModuleProp>
  refs?: Record<string, { title?: string; hint?: string; icon?: string; value: string }>
}

/**
 * What a redirect-based module is handed to build its authorization URL.
 *
 * The framework owns these values rather than each module inventing them: they are generated once per
 * login, kept on the session, and checked when the provider comes back — which is what makes the
 * answer belong to the browser that started the flow. A module that has no use for `nonce` or
 * `codeVerifier` (a plain OAuth2 provider) simply ignores them.
 */
export interface AuthFlow {
  /** Where the provider sends the browser back. Registered with the provider by the administrator. */
  redirectUri: string
  /**
   * Ties the callback back to the browser that started this login. Threaded differently by every
   * protocol, since only OAuth2/OIDC define a `state` parameter of their own:
   *
   *   - OAuth2 / OIDC (Google, GitHub, generic OIDC): the native `state` query parameter, round-tripped
   *     by the provider unchanged and read back by the GET `/auth/:strategyId/callback` route.
   *   - SAML: carried in `RelayState`, which the identity provider echoes back as a same-named form
   *     field on the POST it sends the browser to make — see the POST `/auth/:strategyId/callback`
   *     route, and `AuthFlowCallback.body`.
   *   - CAS: CAS defines neither `state` nor anything to echo it back in — it only ever appends its own
   *     `?ticket=` to whatever `service` / `serviceURL` was registered for the login, preserving
   *     whatever query string was already there. So a CAS module's `authorizationUrl()` appends
   *     `state` as a query parameter onto that URL itself before redirecting; CAS hands it straight
   *     back on the GET callback, alongside `ticket`, without ever looking at it.
   */
  state: string
  nonce: string
  /** PKCE verifier, whose challenge goes on the authorization request. */
  codeVerifier: string
  /**
   * SAML only: the `ID` this SP puts on the outbound `AuthnRequest`. Generated by the framework
   * (`api/auth/provider.ts`'s `/auth/:strategyId/authorize` route), not by `@node-saml/node-saml`
   * itself, so it can be written onto `req.session.authFlow` before the request is ever built and
   * read back by `profile()` once the identity provider answers — see `saml/authentication.ts`'s
   * `buildSaml()` for why that round trip is what makes `validateInResponseTo` enforceable at all.
   * Every other protocol either has its own replay protection already (`state` and `nonce`) or
   * simply ignores this, the same way SAML ignores `nonce`/`codeVerifier`.
   */
  authnRequestId?: string
}

/** The same flow, once the provider has come back with an answer. */
export interface AuthFlowCallback extends AuthFlow {
  /** The callback URL as it arrived, query string included — what an OIDC library validates against. */
  currentUrl: string
  /** The authorization code, for a module that reads it directly rather than through a library. */
  code?: string
  /**
   * CAS's equivalent of `code`: the service ticket it granted, read off the same GET callback route's
   * querystring. Absent for every other protocol.
   */
  ticket?: string
  /**
   * The parsed `application/x-www-form-urlencoded` body, for a module whose provider answers with a
   * form POST rather than a redirect — SAML's `SAMLResponse` and `RelayState` arrive this way. Absent
   * on a GET callback.
   */
  body?: Record<string, any>
}

/**
 * Who signed in, as a module reports them.
 *
 * `id` is the provider's own identifier for the account and never changes — it is what
 * `findOrCreateProviderUser()` binds an existing account to and checks on every later login, since
 * `email` alone is not proof of identity: a provider that can be made to assert an arbitrary address
 * would otherwise be able to sign in as whichever account already used it. `email` is what a *new*
 * account is created and matched by, and what an existing, already-linked account's login is re-checked
 * against `allowedEmailRegex` with. A module must not return an address it has not established belongs
 * to the person — an unverified one is how somebody signs in as somebody else.
 */
export interface ProviderProfile {
  id: string
  email: string
  name: string
  /**
   * Group names as the provider reports them, for a strategy configured with `mapGroups: true`. Absent
   * (rather than empty) means the module did not look — `undefined` and `[]` are different answers, and
   * only the former leaves the user's wiki-side group membership untouched. See
   * `models/users.ts`'s `syncProviderGroups()`.
   */
  groups?: string[]
}

/**
 * Thrown by a form-based module's (`useForm: true`, e.g. LDAP) `authenticate()` when the credentials
 * checked out at the provider but no local account matches yet.
 *
 * A redirect-based provider always goes through `loginWithProvider()`, which finds-or-creates the
 * account itself; a form-based one calls straight into `authenticate()` from `login()` and has no other
 * way to hand back "this person is real, here is who they are, but there is no account for them yet" —
 * this is that signal. `login()` catches it and, if the strategy accepts new users, provisions the
 * account through the same find-or-create path a redirect-based provider uses (see
 * `models/users.ts`'s `findOrCreateProviderUser()`).
 */
export class ProvisionableLoginError extends Error {
  profile: ProviderProfile

  constructor(profile: ProviderProfile) {
    super('ERR_USER_NOT_FOUND_PROVISIONABLE')
    this.name = 'ProvisionableLoginError'
    this.profile = profile
  }
}

/** A configured instance of an authentication module. */
export interface AuthStrategy {
  id: string
  module: string
  displayName: string
  isEnabled: boolean
  /** Whether a visitor may create their own account through this strategy's own form. Only ever
   *  enforced for a form-based module -- see `models/users.ts#register()`. */
  selfRegistration: boolean
  /** Whether an account is created automatically for somebody a redirect-based provider signs in for
   *  the first time. Only ever enforced for a redirect-based module -- see
   *  `models/users.ts#findOrCreateProviderUser()`. */
  autoProvision: boolean
  allowedEmailRegex: string
  /**
   * Admin-facing alternative to `allowedEmailRegex` for the common case: a list of domains instead
   * of a hand-written pattern. Matched case-insensitively, stored here already normalized (trimmed,
   * lower-cased, deduped) by `createStrategy`/`updateStrategy`. Only ever enforced for local
   * self-registration (`models/login.ts#register()`, `assertAllowedRegistrationDomain`) -- unlike
   * `allowedEmailRegex` above, this does not gate provider auto-provisioning. Empty means
   * unrestricted. Independent of `allowedEmailRegex`; both may be set on the same strategy.
   */
  allowedEmailDomains: string[]
  autoEnrollGroups: string[]
  /**
   * Off by default. An existing account is only ever claimed by a provider login when this is on for
   * that strategy — otherwise a matching email address with no stored link is refused rather than
   * silently bound. See `models/users.ts#findOrCreateProviderUser()`.
   */
  trustEmailForLinking: boolean
  /** Admin-chosen subset of groups `syncProviderGroups()` is allowed to grant/revoke. Empty means none. */
  mappableGroups: string[]
  config: Record<string, any>
}

/** The module every wiki ships with. */
const LOCAL_MODULE = 'local'

/** A bare domain: at least one label, a dot, and a TLD label -- no `@`, no scheme, no path. */
const DOMAIN_PATTERN =
  /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$/i

/**
 * Trim, lower-case and dedupe a submitted domain list, dropping empty entries.
 *
 * Case-insensitivity is applied at write time rather than left to whatever later reads the column,
 * so every consumer (enforcement, the admin form re-showing it) sees the one canonical form.
 */
function normalizeEmailDomains(domains: string[]): string[] {
  const seen = new Set<string>()
  for (const raw of domains) {
    const domain = raw.trim().toLowerCase()
    if (domain) {
      seen.add(domain)
    }
  }
  return [...seen]
}

/**
 * Whether this is the strategy the instance was seeded with.
 *
 * Not merely "a local strategy": every account's password is stored under this exact strategy ID
 * (see `models/users.ts`), so it is the one that cannot be disabled or deleted. A second instance of
 * the local module holds no credentials and is as disposable as any other strategy.
 */
function isBuiltInLocal(id: string): boolean {
  return id === WIKI.data.systemIds.localAuthId
}

/**
 * Authentication model
 */
class Authentication {
  async getStrategies({ enabledOnly = false }: { enabledOnly?: boolean } = {}) {
    return WIKI.db
      .select()
      .from(authenticationTable)
      .where(enabledOnly ? eq(authenticationTable.isEnabled, true) : undefined)
  }

  /**
   * The authentication modules found on disk, in the order the admin area lists them
   */
  getModules(): AuthModule[] {
    return [...((WIKI.data.authentication ?? []) as AuthModule[])].sort((a, b) =>
      a.key === LOCAL_MODULE ? -1 : b.key === LOCAL_MODULE ? 1 : a.title.localeCompare(b.title)
    )
  }

  /**
   * A single module definition, or null when nothing on disk declares that key
   */
  getModule(key: string): AuthModule | null {
    return this.getModules().find((m) => m.key === key) ?? null
  }

  /**
   * Every configured strategy, the built-in local one first, then alphabetically by display name.
   *
   * Config values are completed from the module's declared defaults, so a prop added to a module
   * after a strategy was configured is returned with its default rather than as a missing key.
   *
   * @param opts.mask When true, a `sensitive` prop's stored value (an OAuth client secret, an LDAP
   *   bind password, ...) is replaced with a mask before being returned -- see
   *   `helpers/moduleProps.ts#maskSensitiveConfig`. Defaults to false: `updateStrategy()`'s own merge
   *   reads through this method too, and needs the real values to preserve an untouched secret
   *   correctly. The actual login flow never reads config from here at all -- it goes through the
   *   raw `getStrategies()` below, used only to build `WIKI.auth.strategies` -- so masking here by
   *   default would not even protect that path, only complicate this one. Only an admin-facing read
   *   that serializes `config` straight into an HTTP response should pass `{ mask: true }`.
   */
  async getActiveStrategies({ mask = false }: { mask?: boolean } = {}): Promise<AuthStrategy[]> {
    const strategies = await WIKI.db
      .select()
      .from(authenticationTable)
      .orderBy(asc(authenticationTable.displayName))
    return strategies
      .map((stg) => {
        const config = this.buildConfig(stg.module, {}, stg.config as Record<string, any>)
        return {
          ...stg,
          allowedEmailDomains: stg.allowedEmailDomains ?? [],
          autoEnrollGroups: stg.autoEnrollGroups ?? [],
          mappableGroups: stg.mappableGroups ?? [],
          config: mask
            ? maskSensitiveConfig(this.getModule(stg.module)?.props ?? {}, config)
            : config
        }
      })
      .sort((a, b) => (isBuiltInLocal(a.id) ? -1 : isBuiltInLocal(b.id) ? 1 : 0))
  }

  /**
   * A single configured strategy, or null if there is no such strategy
   */
  async getStrategyById(id: string, opts?: { mask?: boolean }): Promise<AuthStrategy | null> {
    return (await this.getActiveStrategies(opts)).find((stg) => stg.id === id) ?? null
  }

  /**
   * Every group currently at risk of being silently reverted by `models/login.ts#syncProviderGroups()`
   * on the account's next login through an enabled, group-mapping strategy — one entry per group,
   * naming every strategy that could do the reverting (WP #2440: the admin UI had no warning that a
   * manually-added membership in one of these groups may not survive the user's next provider login).
   *
   * Carries no secrets — only group ids and strategy display names — unlike `getActiveStrategies()`,
   * so it is reachable by a `manage:users`/`manage:groups` holder, not only `manage:system`.
   */
  async getGroupSyncWarnings(): Promise<GroupSyncWarning[]> {
    const strategies = await this.getActiveStrategies()
    const mapping = strategies.filter((stg) => stg.isEnabled && stg.config?.mapGroups)
    if (mapping.length < 1) {
      return []
    }
    const guestsGroupId = WIKI.data.systemIds.guestsGroupId
    const rootAdminGroupId = WIKI.config.auth.rootAdminGroupId
    const systemGroupIds = await WIKI.models.groups.systemGroupIds()

    const byGroup = new Map<string, GroupSyncWarningStrategy[]>()
    for (const stg of mapping) {
      for (const groupId of syncRevocableGroupIds(stg, {
        guestsGroupId,
        rootAdminGroupId,
        systemGroupIds
      })) {
        const strategiesForGroup = byGroup.get(groupId) ?? []
        strategiesForGroup.push({ id: stg.id, displayName: stg.displayName })
        byGroup.set(groupId, strategiesForGroup)
      }
    }
    return [...byGroup.entries()].map(([groupId, strategiesForGroup]) => ({
      groupId,
      strategies: strategiesForGroup
    }))
  }

  /**
   * Merge incoming config values onto the ones already stored, keeping only what the module declares
   * — see `helpers/moduleRegistry.ts#mergeModuleConfig`.
   */
  buildConfig(
    moduleKey: string,
    incoming: Record<string, any> = {},
    existing: Record<string, any> = {}
  ): Record<string, any> {
    return mergeModuleConfig(this.getModule(moduleKey)?.props ?? {}, incoming, existing)
  }

  /**
   * Check incoming config values against what the module declares — see
   * `helpers/moduleRegistry.ts#validateModuleConfig`. An unknown key is dropped by `buildConfig`
   * rather than refused here, so a module losing a prop can never make the admin area unable to save.
   *
   * @returns The reason it is invalid, or null when it is fine
   */
  validateConfig(moduleKey: string, incoming: Record<string, any> = {}): string | null {
    return validateModuleConfig(this.getModule(moduleKey)?.props ?? {}, incoming)
  }

  /**
   * Check the fields shared by every strategy, whichever module it uses.
   *
   * @param strategy The values as they will end up stored, i.e. already merged with the current ones
   * @returns The reason it is invalid, or null when it is fine
   */
  async validateStrategy(strategy: {
    /** Omitted when the strategy does not exist yet, i.e. on create. */
    id?: string
    module: string
    displayName?: string
    isEnabled?: boolean
    allowedEmailRegex?: string
    allowedEmailDomains?: string[]
    autoEnrollGroups?: string[]
    mappableGroups?: string[]
  }): Promise<string | null> {
    if (strategy.displayName !== undefined && strategy.displayName.trim().length < 1) {
      return 'The display name cannot be empty.'
    }
    if (strategy.id && isBuiltInLocal(strategy.id) && strategy.isEnabled === false) {
      return 'The built-in local strategy cannot be disabled, as it would leave no way to log in.'
    }
    if (strategy.allowedEmailRegex) {
      try {
        new RegExp(strategy.allowedEmailRegex)
      } catch (err: any) {
        return `The allowed email pattern is not a valid regular expression: ${err.message}`
      }
    }
    if (strategy.allowedEmailDomains) {
      const invalidDomain = normalizeEmailDomains(strategy.allowedEmailDomains).find(
        (domain) => !DOMAIN_PATTERN.test(domain)
      )
      if (invalidDomain) {
        return `"${invalidDomain}" is not a valid domain.`
      }
    }
    if (strategy.autoEnrollGroups && strategy.autoEnrollGroups.length > 0) {
      if (strategy.autoEnrollGroups.includes(WIKI.data.systemIds.guestsGroupId)) {
        return 'The guests group cannot be used for auto-enrollment.'
      }
      const existing = await WIKI.db.select({ id: groupsTable.id }).from(groupsTable)
      const existingIds = existing.map((g) => g.id)
      const unknown = strategy.autoEnrollGroups.find((id) => !existingIds.includes(id))
      if (unknown) {
        return `Group ${unknown} does not exist.`
      }
    }
    if (strategy.mappableGroups && strategy.mappableGroups.length > 0) {
      if (strategy.mappableGroups.includes(WIKI.data.systemIds.guestsGroupId)) {
        return 'The guests group cannot be mapped from a provider.'
      }
      const existing = await WIKI.db.select({ id: groupsTable.id }).from(groupsTable)
      const existingIds = existing.map((g) => g.id)
      const unknown = strategy.mappableGroups.find((id) => !existingIds.includes(id))
      if (unknown) {
        return `Group ${unknown} does not exist.`
      }
    }
    return null
  }

  /**
   * Configure a new instance of a module
   *
   * @returns The new strategy's ID
   */
  async createStrategy(values: {
    module: string
    displayName?: string
    isEnabled?: boolean
    selfRegistration?: boolean
    autoProvision?: boolean
    allowedEmailRegex?: string
    allowedEmailDomains?: string[]
    autoEnrollGroups?: string[]
    trustEmailForLinking?: boolean
    mappableGroups?: string[]
    config?: Record<string, any>
  }): Promise<string> {
    const mod = this.getModule(values.module)!
    const result = await WIKI.db
      .insert(authenticationTable)
      .values({
        module: values.module,
        displayName: values.displayName?.trim() || mod.title,
        isEnabled: values.isEnabled ?? true,
        selfRegistration: values.selfRegistration ?? false,
        autoProvision: values.autoProvision ?? false,
        allowedEmailRegex: values.allowedEmailRegex ?? '',
        allowedEmailDomains: normalizeEmailDomains(values.allowedEmailDomains ?? []),
        autoEnrollGroups: values.autoEnrollGroups ?? [],
        trustEmailForLinking: values.trustEmailForLinking ?? false,
        mappableGroups: values.mappableGroups ?? [],
        config: this.buildConfig(values.module, values.config)
      })
      .returning({ id: authenticationTable.id })

    await this.activateStrategies()
    return result[0].id
  }

  /**
   * Update a configured strategy.
   *
   * The strategies are reloaded afterwards, so a config change takes effect on the next login rather
   * than on the next restart.
   *
   * @returns Whether a strategy was updated
   */
  async updateStrategy(
    id: string,
    patch: {
      displayName?: string
      isEnabled?: boolean
      selfRegistration?: boolean
      autoProvision?: boolean
      allowedEmailRegex?: string
      allowedEmailDomains?: string[]
      autoEnrollGroups?: string[]
      trustEmailForLinking?: boolean
      mappableGroups?: string[]
      config?: Record<string, any>
    }
  ): Promise<boolean> {
    const current = await this.getStrategyById(id)
    if (!current) {
      return false
    }

    const values: Partial<typeof authenticationTable.$inferInsert> = {}
    if (patch.displayName !== undefined) {
      values.displayName = patch.displayName.trim()
    }
    if (patch.isEnabled !== undefined) {
      values.isEnabled = patch.isEnabled
    }
    if (patch.selfRegistration !== undefined) {
      values.selfRegistration = patch.selfRegistration
    }
    if (patch.autoProvision !== undefined) {
      values.autoProvision = patch.autoProvision
    }
    if (patch.allowedEmailRegex !== undefined) {
      values.allowedEmailRegex = patch.allowedEmailRegex
    }
    if (patch.allowedEmailDomains !== undefined) {
      values.allowedEmailDomains = normalizeEmailDomains(patch.allowedEmailDomains)
    }
    if (patch.autoEnrollGroups !== undefined) {
      values.autoEnrollGroups = patch.autoEnrollGroups
    }
    if (patch.trustEmailForLinking !== undefined) {
      values.trustEmailForLinking = patch.trustEmailForLinking
    }
    if (patch.mappableGroups !== undefined) {
      values.mappableGroups = patch.mappableGroups
    }
    if (patch.config !== undefined) {
      values.config = this.buildConfig(current.module, patch.config, current.config)
    }
    if (Object.keys(values).length < 1) {
      return false
    }

    const result = await WIKI.db
      .update(authenticationTable)
      .set(values)
      .where(eq(authenticationTable.id, id))
    if ((result.rowCount ?? 0) < 1) {
      return false
    }

    await this.activateStrategies()
    return true
  }

  /**
   * Delete a configured strategy, and stop every site from offering it.
   *
   * Users whose only credentials belong to this strategy lose their way in, which is why the built-in
   * local strategy — the one every account is seeded against — cannot be deleted.
   *
   * @returns Whether a strategy was deleted
   */
  async deleteStrategy(id: string): Promise<boolean> {
    const result = await WIKI.db.delete(authenticationTable).where(eq(authenticationTable.id, id))
    if ((result.rowCount ?? 0) < 1) {
      return false
    }

    // -> Sites keep their own ordered list of strategy IDs, which would otherwise keep a dangling one
    for (const site of await WIKI.models.sites.getAllSites()) {
      const configured = ((site.config as Record<string, any>)?.authStrategies ?? []) as Array<{
        id: string
      }>
      if (configured.some((s) => s.id === id)) {
        await WIKI.models.sites.updateSite(site.id, {
          config: { authStrategies: configured.filter((s) => s.id !== id) }
        })
      }
    }

    await this.activateStrategies()
    return true
  }

  async refreshStrategiesFromDisk(): Promise<void> {
    // -> Emptied before the scan, not merely reassigned on success: `base.yml` declares no
    //    `authentication` key, and `models/users.ts`'s login/registration paths and
    //    `api/auth/strategies.ts`'s strategy listing all call `WIKI.data.authentication.find(...)`
    //    unguarded. A failed scan has to leave them an empty list to walk, not `undefined` to throw
    //    a 500 on -- the same "reset, then refill" the other module-backed models do in their catch.
    WIKI.data.authentication = []
    try {
      // -> Only a module declaring `isAvailable` is loaded: a definition on disk that this build does
      //    not actually ship an implementation for must not reach the admin area's picker.
      WIKI.data.authentication = await readModuleDefinitions<AuthModule>(
        path.join(WIKI.SERVERPATH, 'modules/authentication'),
        {
          label: 'authentication module',
          parseProps: true,
          skipUnavailable: true,
          logEach: true
        }
      )

      WIKI.logger.info(
        `Loaded ${WIKI.data.authentication.length} authentication module definitions [ OK ]`
      )
    } catch (err: any) {
      WIKI.logger.error('Failed to scan or load authentication module definitions [ FAILED ]')
      WIKI.logger.error(err)
    }
  }

  async activateStrategies(): Promise<void> {
    WIKI.logger.info('Activating authentication strategies...')

    // Unload any active strategies
    try {
      for (const strKey in WIKI.auth.strategies) {
        const strategy = WIKI.auth.strategies[strKey] as any
        if (typeof strategy.destroy === 'function') {
          await strategy.destroy()
        }
      }
    } catch (err: any) {
      WIKI.logger.warn(`Failed to unload active strategies [ FAILED ]`)
      WIKI.logger.warn(err)
    }
    WIKI.auth.strategies = {}

    // Load enabled strategies
    const enabledStrategies = await this.getStrategies({ enabledOnly: true })
    for (const stg of enabledStrategies) {
      try {
        const StrategyModule = (
          await import(`../modules/authentication/${stg.module}/authentication.ts`)
        ).default
        const strategy = new StrategyModule(stg.id, stg.config)
        WIKI.auth.strategies[stg.id] = strategy
        strategy.module = stg.module
        if (typeof strategy.init === 'function') {
          await strategy.init()
        }

        WIKI.logger.info(`Enabled authentication strategy ${stg.displayName} [ OK ]`)
      } catch (err: any) {
        WIKI.logger.error(
          `Failed to enable authentication strategy ${stg.displayName} (${stg.id}) [ FAILED ]`
        )
        WIKI.logger.error(err)
      }
    }
  }

  async init(ids: SystemIds): Promise<void> {
    await WIKI.db.insert(authenticationTable).values({
      id: ids.authModuleId,
      module: 'local',
      isEnabled: true,
      displayName: 'Local Authentication',
      config: {
        emailValidation: true,
        enforceTfa: false
      }
    })
  }
}

export const authentication = new Authentication()
