ALTER TABLE "apiKeys" ALTER COLUMN "expiration" SET DATA TYPE timestamp with time zone USING "expiration" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "apiKeys" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "apiKeys" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "approvalRules" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "approvalRules" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "assets" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "assets" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "auditLog" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "blockCode" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "blockCredentials" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "blockCredentials" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "checklistExecutions" ALTER COLUMN "startedAt" SET DATA TYPE timestamp with time zone USING "startedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "checklistExecutions" ALTER COLUMN "completedAt" SET DATA TYPE timestamp with time zone USING "completedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "checklistItemChecks" ALTER COLUMN "checkedAt" SET DATA TYPE timestamp with time zone USING "checkedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "classificationLevels" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "classificationLevels" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "comments" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "comments" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "contentSyncState" ALTER COLUMN "lastSyncedAt" SET DATA TYPE timestamp with time zone USING "lastSyncedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "contentSyncState" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "contentSyncState" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "glossaryTerms" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "glossaryTerms" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "glossaryVersions" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "groups" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "groups" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "hooks" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "hooks" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "iconSets" ALTER COLUMN "refreshedAt" SET DATA TYPE timestamp with time zone USING "refreshedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "iconSets" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "icons" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "jobHistory" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "jobHistory" ALTER COLUMN "startedAt" SET DATA TYPE timestamp with time zone USING "startedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "jobHistory" ALTER COLUMN "completedAt" SET DATA TYPE timestamp with time zone USING "completedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "jobLock" ALTER COLUMN "lastCheckedAt" SET DATA TYPE timestamp with time zone USING "lastCheckedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "jobSchedule" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "jobSchedule" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "jobs" ALTER COLUMN "waitUntil" SET DATA TYPE timestamp with time zone USING "waitUntil" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "jobs" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "jobs" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "locales" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "locales" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "migrationRecords" ALTER COLUMN "importedAt" SET DATA TYPE timestamp with time zone USING "importedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageEditSubmissionApprovals" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageEditSubmissions" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageEditSubmissions" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageHistory" ALTER COLUMN "versionDate" SET DATA TYPE timestamp with time zone USING "versionDate" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageRenderQueue" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageRenderQueue" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageWatchEvents" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageWatchEvents" ALTER COLUMN "deliveredAt" SET DATA TYPE timestamp with time zone USING "deliveredAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageWatchEvents" ALTER COLUMN "readAt" SET DATA TYPE timestamp with time zone USING "readAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageWatching" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pages" ALTER COLUMN "publishStartDate" SET DATA TYPE timestamp with time zone USING "publishStartDate" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pages" ALTER COLUMN "publishEndDate" SET DATA TYPE timestamp with time zone USING "publishEndDate" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pages" ALTER COLUMN "ratingCount" SET DATA TYPE timestamp with time zone USING "ratingCount" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pages" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pages" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "pageviews" ALTER COLUMN "viewedAt" SET DATA TYPE timestamp with time zone USING "viewedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "rateLimits" ALTER COLUMN "windowStartedAt" SET DATA TYPE timestamp with time zone USING "windowStartedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "rateLimits" ALTER COLUMN "bannedUntil" SET DATA TYPE timestamp with time zone USING "bannedUntil" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "rateLimits" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "sessions" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "sites" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "storage" ALTER COLUMN "lastTickAt" SET DATA TYPE timestamp with time zone USING "lastTickAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "tags" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "tags" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "tree" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "tree" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "userKeys" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "userKeys" ALTER COLUMN "validUntil" SET DATA TYPE timestamp with time zone USING "validUntil" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "lastLoginAt" SET DATA TYPE timestamp with time zone USING "lastLoginAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt" AT TIME ZONE 'UTC';